### PR TITLE
Allow custom handling of non-Boom errors + TypeScript typings

### PR DESCRIPTION
**Pull request by KeithGillette**
Per our discussion on #4, I finally got around to adding a `nonBoomTransformer` to allow custom handling of non-Boom errors. I also took a stab at adding typings, since I use TypeScript.

### CODE REVIEW

**Comment by KeithGillette** [comment]
Hi, @GiladShoham:

Please let me know what you think of the updates in this PR and whether you're likely to approve.

Thanks,
Keith

**Comment by KeithGillette** [comment]
Hi @GiladShoham:

Seems like you're super-busy with Bit. Please let me know whether you're at all likely to respond to this small PR. I'd prefer not to maintain a fork but would really like this functionality that we discussed.

Thanks!
Keith

**Comment by GiladShoham** [comment]
Hi,
Sorry, long time since I visit this repo.
I'll take a look soon and update you.

**Comment by GiladShoham** [comment]
@KeithGillette 
Looks like there are conflicts, please fix them, and I'll merge it.

**Comment by GiladShoham** [comment]
We might want both in the log.
Also please make sure to fix the indentation.
And i still see a conflict for some reason, are you sure you pulled the last origin/master?

**Comment by KeithGillette** [comment]
Hmmm. I'll re-pull master & resubmit. I just tried to resolve the conflict in Github's editor, with which I appear to be incompetent since the indentation is incorrect and a conflict still remains.

Would you prefer two calls to logger for two separate messages or one concatenated like:

```
logger[logger.info ? 'info' : 'log'](`Transform error to boom error: ${err}`);
```

**Comment by GiladShoham** [comment]
I think one will be enough in this case

**Comment by KeithGillette** [comment]
In looking at this again, I think my initial PR failed with conflicts because I had based it on the latest release v2.0.2 [(08590ce)](https://github.com/GiladShoham/graphql-apollo-errors/commit/08590ced3fa5f8188453a8b8e90f73809d598ead) but I see that _master_ is actually [3 commits ahead with unreleased changes](https://github.com/GiladShoham/graphql-apollo-errors/compare/v2.0.2...master) [(62758bc)](https://github.com/GiladShoham/graphql-apollo-errors/commit/62758bc37766ac86ca61df51f438d3fb9c4c838c). I assume now that you want me to base changes on 62758bc rather than the v2.0.2 release?

Thanks,
Keith

**Comment by GiladShoham** [comment]
base it on the master's head

**Comment by KeithGillette** [comment]
I am re-opening this PR (with a few new linting/spelling corrections) based on the tip of _master_.

**Pull request merged**
